<?php

namespace Modules\Election\Providers;

use App\Events\CinematicMenuEvent;
use App\Events\DashboardWidgetEvent;
use Illuminate\Support\Facades\Event;
use JeroenNoten\LaravelAdminLte\Events\BuildingMenu;
use Modules\Election\View\Components\DashboardHeaderComponent;
use Modules\Election\View\Components\DashboardWidgetsComponent;
use Nwidart\Modules\Support\ModuleServiceProvider;

class ElectionServiceProvider extends ModuleServiceProvider
{
    /**
     * The name of the module.
     */
    protected string $name = 'Election';

    /**
     * The lowercase version of the module name.
     */
    protected string $nameLower = 'election';

    /**
     * Command classes to register.
     *
     * @var string[]
     */
    // protected array $commands = [];

    /**
     * Provider classes to register.
     *
     * @var string[]
     */
    protected array $providers = [
        EventServiceProvider::class,
        RouteServiceProvider::class,
    ];

    /**
     * Define module schedules.
     *
     * @param $schedule
     */
    // protected function configureSchedules(Schedule $schedule): void
    // {
    //     $schedule->command('inspire')->hourly();
    // }
    public function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        Event::listen(BuildingMenu::class, function (BuildingMenu $event) {
            $event->menu->addAfter('dashboard',
                [
                    'text' => 'Elections',
                    'key' => 'elections',
                    'icon' => 'fas fa-fw fa-vote-yea', // Урна для голосования
                    'submenu' => [
                        [
                            'text' => 'List Elections',
                            'url' => route('election:list')
                        ],
                        [
                            'text' => 'Moderation Queue',
                            'url' => route('moderation')
                        ],
                        [
                            'text' => 'Anti-Fraud Logs',
                            'url' => route('logs')
                        ],
                    ]
                ]);
        });

        Event::listen(DashboardWidgetEvent::class, function (DashboardWidgetEvent $event) {
            $event->addHeader((new DashboardHeaderComponent())->render());
            $event->addWidget((new DashboardWidgetsComponent())->render());
        });

        Event::listen(CinematicMenuEvent::class, function (CinematicMenuEvent $event) {
            $event->add([
                'key' => 'tree',
                'label' => 'Tree',
                'url' => '/#tree',
                'children' => [
                    ['label' => 'Engravings', 'url' => '/engravings'],
                    ['label' => 'Golden Leaves', 'url' => '/golden-leaves'],
                    ['label' => 'Human Handprint', 'url' => '/human-handprint'],
                ]
            ]);
            $event->add([
                'key' => 'story',
                'label' => 'Story',
                'url' => '/story',
            ]);
            $event->add([
                'key' => 'voting',
                'label' => 'Voting',
                'url' => '/voting',
            ]);
            $event->add([
                'key' => 'about',
                'label' => 'About',
                'url' => '/about',
            ]);
        });
    }
}
