<?php

namespace Modules\Election\Providers;

use Illuminate\Support\Facades\Event;
use JeroenNoten\LaravelAdminLte\Events\BuildingMenu;
use Nwidart\Modules\Support\ModuleServiceProvider;

class ElectionServiceProvider extends ModuleServiceProvider
{
    /**
     * The name of the module.
     */
    protected string $name = 'Election';

    /**
     * The lowercase version of the module name.
     */
    protected string $nameLower = 'election';

    /**
     * Command classes to register.
     *
     * @var string[]
     */
    // protected array $commands = [];

    /**
     * Provider classes to register.
     *
     * @var string[]
     */
    protected array $providers = [
        EventServiceProvider::class,
        RouteServiceProvider::class,
    ];

    /**
     * Define module schedules.
     *
     * @param $schedule
     */
    // protected function configureSchedules(Schedule $schedule): void
    // {
    //     $schedule->command('inspire')->hourly();
    // }
    public function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        Event::listen(BuildingMenu::class, function (BuildingMenu $event) {
            $event->menu->addAfter('dashboard',
                [
                    'text' => 'Elections',
                    'key' => 'elections',
                    'icon' => 'fas fa-fw fa-vote-yea', // Урна для голосования
                    'submenu' => [
                        [
                            'text' => 'List Elections',
                            'url' => route('election:list')
                        ],
                        [
                            'text' => 'Moderation Queue',
                            'url' => route('moderation')
                        ],
                        [
                            'text' => 'Anti-Fraud Logs',
                            'url' => route('logs')
                        ],
                    ]
                ],);
        });
    }
}
