import type {HomeLanguage} from "@/features/home/copy";

const en = {
  emptyField: "Please complete this field.",
  humanity: "HUMANITY CHOOSES",
  eyebrow: "A place in our shared history",
  intro: "Each month, your vote honours one person with a Golden Leaf.",
  closes: "Voting closes in",
  closed: "This demonstration round has ended.",
  days: "Days",
  hours: "Hours",
  minutes: "Minutes",
  seconds: "Seconds",
  round: "Round 01 / 50",
  view: "View nominees",
  list: "List",
  map: "World map",
  nominate: "Nominate someone",
  search: "Search nominees",
  searchCountries: "Search countries",
  allCountries: "All countries",
  world: "All continents",
  country: "Country",
  countries: "countries",
  sort: "Sort",
  mostVotes: "Most votes",
  alphabetical: "Name A–Z",
  mostNominees: "Most nominees",
  rank: "Rank",
  nominee: "Nominee",
  nominees: "nominees",
  votes: "Votes",
  select: "Select",
  selected: "Selected",
  choose: "Choose a nominee",
  vote: "Vote",
  voted: "Vote recorded",
  about: "About the vote",
  demo: "Demonstration data",
  demoDetail:
    "Fictional nominees and supporters. This preview does not collect real votes or create accounts.",
  exploreCountry: "Explore by country",
  mapHint: "Open a continent. Select a country to discover its nominees.",
  browseHint: "Browse any country. Vote in the global round.",
  viewAll: "View all nominees",
  noResults: "No nominees found",
  noResultsDetail: "Try another name or country, or clear your filters.",
  noCountries: "No countries found",
  clear: "Clear filters",
  previous: "Previous page",
  next: "Next page",
  page: "Page",
  of: "of",
  close: "Close profile",
  back: "Back",
  backToNominees: "Back to nominees",
  profile: "Nominee profile",
  activity: "A life dedicated to",
  reason: "Why this person was nominated",
  qualities: "What they stand for",
  contribution: "Actions that make a difference",
  supporters: "People supporting this nominee",
  supporter: "Supporter",
  voteFor: "Vote for",
  confirmTitle: "A choice that matters.",
  confirmText:
    "You are choosing this nominee in Round 01 of 50. Confirm to preview the voting result.",
  confirm: "Confirm demo vote",
  cancel: "Go back",
  successTitle: "Your choice, a lasting mark.",
  successText:
    "Your demonstration vote has been recorded for this visit. Thank you for exploring Humanity Chooses.",
  alreadyVoted: "You have already cast your demonstration vote in this visit.",
  nominateTitle: "Whose story should be remembered?",
  nominateIntro:
    "Tell us about someone whose actions deserve a place in our shared history.",
  firstName: "First name",
  lastName: "Last name",
  occupation: "Field of activity",
  nominationReason: "Reason for nomination",
  review: "Review nomination",
  reviewTitle: "A story worth sharing.",
  submit: "Preview submission",
  nominationSuccess: "Your nomination is ready.",
  nominationSuccessText:
    "This is a preview of the submission experience. No information has been sent or saved.",
  minimumReason: "At least 40 characters",
  requiredCountry: "Choose a country",
  edit: "Edit details",
  aboutTitle: "One name. One leaf.",
  aboutText:
    "Humanity Chooses brings people together to recognise lives of extraordinary care, courage and contribution. The programme envisions fifty monthly rounds, with one name recognised on a Golden Leaf in each round.",
  aboutSecond:
    "Explore the nominees, read their stories and choose the person whose contribution speaks to you. This first interface preview uses a 90-day demonstration round.",
  aboutLeaf: "50 Golden Leaves",
  aboutRounds: "50 rounds",
  aboutNames: "50 names",
  showFilters: "Filters",
  hideFilters: "Hide filters",
  demoVoter: "You · demo visitor",
};
type VotingCopy = { readonly [K in keyof typeof en]: string };
export const votingCopy: Record<HomeLanguage, VotingCopy> = {
  en,
  ru: {
    emptyField: "Заполните это поле.",
    humanity: "ЧЕЛОВЕЧЕСТВО ВЫБИРАЕТ",
    eyebrow: "Место в нашей общей истории",
    intro: "Каждый месяц ваш голос отмечает одного человека Золотым Листом.",
    closes: "До завершения голосования",
    closed: "Демонстрационный раунд завершён.",
    days: "Дней",
    hours: "Часов",
    minutes: "Минут",
    seconds: "Секунд",
    round: "Раунд 01 / 50",
    view: "Смотреть номинантов",
    list: "Список",
    map: "Карта мира",
    nominate: "Предложить кандидата",
    search: "Поиск номинантов",
    searchCountries: "Поиск стран",
    allCountries: "Все страны",
    world: "Все континенты",
    country: "Страна",
    countries: "стран",
    sort: "Порядок",
    mostVotes: "По голосам",
    alphabetical: "По алфавиту",
    mostNominees: "По числу номинантов",
    rank: "Место",
    nominee: "Номинант",
    nominees: "номинантов",
    votes: "Голоса",
    select: "Выбрать",
    selected: "Выбран",
    choose: "Выберите номинанта",
    vote: "Голосовать",
    voted: "Голос учтён",
    about: "О голосовании",
    demo: "Демонстрационные данные",
    demoDetail:
      "Номинанты и участники вымышлены. В этой версии реальные голоса не собираются и аккаунты не создаются.",
    exploreCountry: "Откройте страны",
    mapHint:
      "Откройте континент. Выберите страну, чтобы увидеть её номинантов.",
    browseHint: "Изучайте страны. Участвуйте в общем раунде.",
    viewAll: "Все номинанты",
    noResults: "Номинанты не найдены",
    noResultsDetail: "Попробуйте другое имя или страну либо сбросьте фильтры.",
    noCountries: "Страны не найдены",
    clear: "Сбросить фильтры",
    previous: "Предыдущая страница",
    next: "Следующая страница",
    page: "Страница",
    of: "из",
    close: "Закрыть профиль",
    back: "Назад",
    backToNominees: "К номинантам",
    profile: "Профиль номинанта",
    activity: "Дело жизни",
    reason: "Почему предложили этого человека",
    qualities: "Качества и убеждения",
    contribution: "Поступки, которые меняют мир",
    supporters: "Кто поддерживает номинанта",
    supporter: "Участник",
    voteFor: "Голосовать за",
    confirmTitle: "Выбор имеет значение.",
    confirmText:
      "Вы выбираете этого номинанта в раунде 01 из 50. Подтвердите выбор, чтобы увидеть тестовый результат.",
    confirm: "Подтвердить тестовый голос",
    cancel: "Вернуться",
    successTitle: "Ваш выбор оставляет след.",
    successText:
      "Тестовый голос учтён на время этого посещения. Спасибо за знакомство с Humanity Chooses.",
    alreadyVoted: "Вы уже отдали тестовый голос во время этого посещения.",
    nominateTitle: "Чью историю стоит сохранить?",
    nominateIntro:
      "Расскажите о человеке, чьи поступки заслуживают места в нашей общей истории.",
    firstName: "Имя",
    lastName: "Фамилия",
    occupation: "Сфера деятельности",
    nominationReason: "Причина номинации",
    review: "Проверить номинацию",
    reviewTitle: "История, которой стоит поделиться.",
    submit: "Посмотреть результат отправки",
    nominationSuccess: "Ваша номинация готова.",
    nominationSuccessText:
      "Это демонстрация отправки заявки. Информация не отправлена и не сохранена.",
    minimumReason: "Не менее 40 символов",
    requiredCountry: "Выберите страну",
    edit: "Изменить данные",
    aboutTitle: "Одно имя. Один лист.",
    aboutText:
      "Humanity Chooses объединяет людей, чтобы отметить заботу, смелость и вклад в жизнь общества. Программа предусматривает пятьдесят ежемесячных раундов: по одному имени на Золотом Листе в каждом раунде.",
    aboutSecond:
      "Изучайте номинантов, читайте их истории и выбирайте человека, чей вклад вам близок. В этой версии интерфейса установлен демонстрационный раунд на 90 дней.",
    aboutLeaf: "50 Золотых Листьев",
    aboutRounds: "50 раундов",
    aboutNames: "50 имён",
    showFilters: "Фильтры",
    hideFilters: "Скрыть фильтры",
    demoVoter: "Вы · тестовый участник",
  },
  es: {
    emptyField: "Completa este campo.",
    humanity: "LA HUMANIDAD ELIGE",
    eyebrow: "Un lugar en nuestra historia compartida",
    intro: "Cada mes, tu voto honra a una persona con una Hoja de Oro.",
    closes: "La votación termina en",
    closed: "Esta ronda de demostración ha terminado.",
    days: "Días",
    hours: "Horas",
    minutes: "Minutos",
    seconds: "Segundos",
    round: "Ronda 01 / 50",
    view: "Ver nominados",
    list: "Lista",
    map: "Mapa mundial",
    nominate: "Nominar a alguien",
    search: "Buscar nominados",
    searchCountries: "Buscar países",
    allCountries: "Todos los países",
    world: "Todos los continentes",
    country: "País",
    countries: "países",
    sort: "Orden",
    mostVotes: "Más votos",
    alphabetical: "Nombre A–Z",
    mostNominees: "Más nominados",
    rank: "Puesto",
    nominee: "Nominado",
    nominees: "nominados",
    votes: "Votos",
    select: "Elegir",
    selected: "Elegido",
    choose: "Elige un nominado",
    vote: "Votar",
    voted: "Voto registrado",
    about: "Sobre la votación",
    demo: "Datos de demostración",
    demoDetail:
      "Nominados y votantes ficticios. Esta vista previa no recoge votos reales ni crea cuentas.",
    exploreCountry: "Explora por país",
    mapHint:
      "Abre un continente. Selecciona un país para descubrir sus nominados.",
    browseHint: "Explora cualquier país. Vota en la ronda global.",
    viewAll: "Ver todos los nominados",
    noResults: "No se encontraron nominados",
    noResultsDetail: "Prueba otro nombre o país, o borra los filtros.",
    noCountries: "No se encontraron países",
    clear: "Borrar filtros",
    previous: "Página anterior",
    next: "Página siguiente",
    page: "Página",
    of: "de",
    close: "Cerrar perfil",
    back: "Volver",
    backToNominees: "Volver a nominados",
    profile: "Perfil del nominado",
    activity: "Una vida dedicada a",
    reason: "Por qué se nominó a esta persona",
    qualities: "Sus valores",
    contribution: "Acciones que marcan la diferencia",
    supporters: "Personas que apoyan a este nominado",
    supporter: "Participante",
    voteFor: "Votar por",
    confirmTitle: "Una elección que importa.",
    confirmText:
      "Estás eligiendo a este nominado en la ronda 01 de 50. Confirma para ver el resultado de prueba.",
    confirm: "Confirmar voto de prueba",
    cancel: "Volver",
    successTitle: "Tu elección deja huella.",
    successText:
      "Tu voto de prueba se ha registrado durante esta visita. Gracias por descubrir Humanity Chooses.",
    alreadyVoted: "Ya has emitido tu voto de prueba durante esta visita.",
    nominateTitle: "¿Qué historia debemos recordar?",
    nominateIntro:
      "Cuéntanos sobre alguien cuyas acciones merecen un lugar en nuestra historia compartida.",
    firstName: "Nombre",
    lastName: "Apellido",
    occupation: "Actividad",
    nominationReason: "Motivo de la nominación",
    review: "Revisar nominación",
    reviewTitle: "Una historia que compartir.",
    submit: "Ver envío de prueba",
    nominationSuccess: "Tu nominación está lista.",
    nominationSuccessText:
      "Esta es una demostración del envío. No se ha enviado ni guardado información.",
    minimumReason: "Al menos 40 caracteres",
    requiredCountry: "Selecciona un país",
    edit: "Editar datos",
    aboutTitle: "Un nombre. Una hoja.",
    aboutText:
      "Humanity Chooses reúne a personas para reconocer vidas de cuidado, valentía y contribución. El programa contempla cincuenta rondas mensuales, cada una dedicada a un nombre en una Hoja de Oro.",
    aboutSecond:
      "Explora a los nominados, lee sus historias y elige a la persona cuya contribución te inspire. Esta primera versión utiliza una ronda de demostración de 90 días.",
    aboutLeaf: "50 Hojas de Oro",
    aboutRounds: "50 rondas",
    aboutNames: "50 nombres",
    showFilters: "Filtros",
    hideFilters: "Ocultar filtros",
    demoVoter: "Tú · visitante de prueba",
  },
};
